version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dociebie}
      POSTGRES_USER: ${POSTGRES_USER:-dociebie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dociebie_secret}
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh
    volumes:
      - backend_media:/app/media
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  backend_media: