# Generated by Django 5.1.4 on 2026-02-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzona'), ('paid', 'Opłacono'), ('unpaid', 'Nieopłacono'), ('completed', 'Zakończono'), ('cancelled', 'Anulowano')], default='pending', max_length=20),
        ),
    ]
