# Generated by Django 5.1.4 on 2026-02-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('scissors', 'Nożyczki (fryzjer/barber)'), ('sparkles', 'Iskierki (kosmetyka/SPA)'), ('leaf', 'Liść (ogrodnictwo)'), ('home', 'Dom (sprzątanie)'), ('wrench', 'Klucz (naprawa)'), ('truck', 'Ciężarówka (przeprowadzka/kurier)'), ('camera', 'Kamera (filmowanie/foto)'), ('heart', 'Serce (zdrowie/wellness)'), ('car', 'Samochód (motoryzacja)'), ('paw', 'Łapka (zwierzęta)')], default='', max_length=50),
        ),
    ]
