# Generated by Django 5.1.4 on 2026-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salon',
            name='bank_holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salon',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
