# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salon_bank_account_number_salon_bank_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='details_image',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='reviews_image',
        ),
    ]
