# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_remove_salon_details_image_remove_salon_reviews_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='services_image',
        ),
    ]
