# Generated by Django 5.1.4 on 2026-02-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_restructure_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
